### ISSUE TITLE
MSANet 

### ISSUE THREAD

**Issue by Ehteshamciitwah** [cmhungsteve/Awesome-Transformer-Attention#10]
Kindly add newly **Few-Shot Segmentation SOTA** Paper.
MSANet: Multi-Similarity and Attention Guidance for Boosting Few-Shot Segmentation
https://arxiv.org/abs/2206.09667
https://paperswithcode.com/paper/msanet-multi-similarity-and-attention-1

**Comment by cmhungsteve** [comment]
Thank you for sharing.
I just added it.
