### ISSUE TITLE
Transformer on Sample Relationship Exploration

### ISSUE THREAD

**Issue by zhihou7** [cmhungsteve/Awesome-Transformer-Attention#2]
Hi, Thanks for your conclusion!

I think our recent work might be also a typical Transformer Attention for sample relationship exploration: CVPR2022, BatchFormer: Learning to Explore Sample Relationships for Robust Representation Learning, https://arxiv.org/abs/2203.01522. There is also a general version in [BatchFormerV2](https://arxiv.org/abs/2204.01254), in which we present the consistent effectiveness on object detection, panoptic segmentation, and image classification.

If you also think so, it would be better to include this paper.

Regards,

**Comment by cmhungsteve** [comment]
Hello @zhihou7, 
This list already includes the two papers you mentioned above.
Thank you.

**Comment by zhihou7** [comment]
Sincerely sorry for that. Thank you very much. I merely checked the list in Transfer Learning (domain generalization). Btw, BatchFormerV2 is closer to object detection since this paper is verified to be plug-and-play to DETR-based methods with massive experiments.

Regards,

**Comment by cmhungsteve** [comment]
Thank you for your suggestion.
Actually, I plan to reorganize the categories of the list in the near future to make it better categorize the papers.
