### ISSUE TITLE
Two Pruning Papers for Transformer in NeurIPS 2022

### ISSUE THREAD

**Issue by ChuanyangZheng** [cmhungsteve/Awesome-Transformer-Attention#21]
Kindly add two papers about pruning (compression) for transformer appeared in NeurIPS 2022.
1. [Optimal Brain Compression: A Framework for Accurate Post-Training Quantization and Pruning](https://openreview.net/forum?id=ksVGCOlOEba)
2. [A Fast Post-Training Pruning Framework for Transformers](https://openreview.net/forum?id=0GRBKLBjJE)

**Comment by cmhungsteve** [comment]
Thank you for sharing.
However, it seems that these two papers are for Transformers, not Vision Transformers, which is out of this repo's scope.
