### ISSUE TITLE
Hello. Great work!

### ISSUE THREAD

**Issue by wjun0830** [cmhungsteve/Awesome-Transformer-Attention#37]
Hello! Great work!

I would like to introduce CVPR2023 paper called QD-DETR (Query-Dependent Detection Transformer). (multi-modal retrieval branch)
Paper : Query-Dependent Video Representation for Moment Retrieval and Highlight Detection
arxiv link : https://arxiv.org/abs/2303.13874
Github link : https://github.com/wjun0830/QD-DETR

Thank you.

**Comment by cmhungsteve** [comment]
Thank you for your comments.
This paper is already in the list
