### ISSUE TITLE
request to add a paper

### ISSUE THREAD

**Issue by shashankvkt** [cmhungsteve/Awesome-Transformer-Attention#38]
Hi,
Thanks for this amazing collection. It really help me get a nice literature survey for our work. We also propose to improve efficiency in vision transformer and was wondering if you could please add our paper to the collection.  
  
***Skip-Attention: Improving Vision Transformers by Paying Less Attention*** - [Arxiv](https://arxiv.org/pdf/2301.02240.pdf). 

Thanks

**Comment by cmhungsteve** [comment]
Thank you for sharing.
Just added your paper.

**Comment by shashankvkt** [comment]
thanks a lot!
