### ISSUE TITLE
You may consider the integration of my collected papers

### ISSUE THREAD

**Issue by junchen14** [cmhungsteve/Awesome-Transformer-Attention#4]
Hi, thanks for your works, and I like it very much.

You may also consider to integrate my collected papers into your git, I found there are several missing papers can be complementary to your collection. 

https://github.com/junchen14/Multi-Modal-Transformer

**Comment by cmhungsteve** [comment]
Thank you for sharing.
I will check that.

**Comment by junchen14** [comment]
You are very welcome, 

Let me know if there is anything I can help with. I am happy to do the contribution.

**Comment by cmhungsteve** [comment]
I would be appreciative if you can add the missing papers and submit a pull request.
Thank you.

**Comment by junchen14** [comment]
sure, I can help with this during my free time
