### ISSUE TITLE
Request to add a paper 

### ISSUE THREAD

**Issue by sauradip** [cmhungsteve/Awesome-Transformer-Attention#40]
Hi,

Thanks for maintaining this awesome repository. 
We have a paper : https://arxiv.org/abs/2303.14863 that uses DETR for diffusion. We think this is relevant to the awesome repository you are maintaining. 

Can this be added to the list  ? 

Thank you in advance

**Comment by cmhungsteve** [comment]
Thank you for sharing.
Just added your paper.
