### ISSUE TITLE
ICCV 2023 SparseBEV

### ISSUE THREAD

**Issue by MiraclesinWang** [cmhungsteve/Awesome-Transformer-Attention#44]
Hello, thanks for your great efforts of collecting papers for reference. Our paper SparseBEV[[arXiv]](https://arxiv.org/abs/2308.09244)[[github]](https://github.com/MCG-NJU/SparseBEV) has recently been accepted to ICCV 2023. Please include our paper in your list.

**Comment by cmhungsteve** [comment]
Hello, 

SparseBEV is already in the list:
https://github.com/cmhungsteve/Awesome-Transformer-Attention/blob/main/README_2.md

Thank you.
