### ISSUE TITLE
add DearKD(CVPR2022)

### ISSUE THREAD

**Issue by boykac** [cmhungsteve/Awesome-Transformer-Attention#6]
training+transformer

title: DearKD: Data-Efficient Early Knowledge Distillation for Vision Transformers
paper link: https://arxiv.org/abs/2204.12997

Thanks

**Comment by cmhungsteve** [comment]
It is already on the list.
Thanks.

![image](https://user-images.githubusercontent.com/17039429/174505446-e103476e-7b25-401c-aa00-c33917e2241d.png)

**Comment by cmhungsteve** [comment]
"Training+Transformer" is mainly for self-supervised learning and pre-training.

**Comment by cmhungsteve** [comment]
Hello @boykac, 

I would be appreciative if you can provide any feedback.
If there is no further question, I will close this issue.
Thank you.

**Comment by boykac** [comment]
please close, thanks for your work!
