### ISSUE TITLE
Code and project page of SPoVT

### ISSUE THREAD

**Issue by peterjohnsonhuang** [cmhungsteve/Awesome-Transformer-Attention#65]
Hi, 
I am one of the first author of "SPoVT: Semantic-Prototype Variational Transformer for Dense Point Cloud Semantic Completion". Thanks for mentioning our in this repo. I am happy to tell you that we finally established our project page and release our code (after an entire year lol). Here's the link: 
project page: https://haoyuhsu.github.io/spovt/index.html
code: https://github.com/haoyuhsu/spovt

Thank you!

**Comment by cmhungsteve** [comment]
Updated. Thank you for sharing!
