### ISSUE TITLE
Requesting to add four papers published in 2022 and 2023

### ISSUE THREAD

**Issue by ShramanPramanick** [cmhungsteve/Awesome-Transformer-Attention#66]
Please add the following four papers which use transformer backbones:

1. Egocentric Video-language pre-training and solves video-text retrieval, video classification, text-guided video grounding, text-guided video summarization, video question-answering etc.

- EgoVLPv2: Egocentric Video-Language Pre-training with Fusion in the Backbone (ICCV 2023) [[Paper](https://arxiv.org/pdf/2307.05463.pdf)] [[Code](https://github.com/facebookresearch/EgoVLPv2)] [[Project](https://shramanpramanick.github.io/EgoVLPv2/)] [[Poster](https://shramanpramanick.github.io/EgoVLPv2/static/images/EgoVLPv2_Poster_ICCV_2023.pdf)]

- Egocentric Video-Language Pretraining (NeurIPS 2022) [[Paper](https://arxiv.org/abs/2206.01670)] [[Code](https://github.com/showlab/EgoVLP)] [[Project](https://qinghonglin.github.io/EgoVLP/)] [[Poster](https://qinghonglin.github.io/EgoVLP/static/images/poster.pdf)]

2. Image-language pre-training and solves image captioning, image-text retrieval, object detection, segmentation, referring expression comprehension.

- VoLTA: Vision-Language Transformer with Weakly-Supervised Local-Feature Alignment (TMLR 2023) [[Paper](https://arxiv.org/pdf/2307.05463.pdf)] [[Code](https://github.com/ShramanPramanick/VoLTA)] [[Project](https://shramanpramanick.github.io/VoLTA/)]

3. Video temporal grounding, unifying diverse temporal annotations to power moment retrieval (interval), highlight detection (curve) and video summarization (point).

- UniVTG: Towards Unified Video-Language Temporal Grounding (ICCV 2023) [[Paper](https://arxiv.org/abs/2307.16715)] [[Code](https://github.com/showlab/UniVTG)]

**Comment by cmhungsteve** [comment]
Thank you for sharing, @ShramanPramanick. 
I have updated the repo with the papers above.
