### ISSUE TITLE
Adding Official Code for ViTGAN

### ISSUE THREAD

**Issue by kjunelee** [cmhungsteve/Awesome-Transformer-Attention#7]
Dear Min-Hung,

Thank you for creating a great list of Transformers for computer vision.

Could you please add the official code link for the ViTGAN paper?
https://github.com/mlpc-ucsd/ViTGAN

Thank you for your consideration!

**Comment by cmhungsteve** [comment]
Just added it.
I think you can also update your arXiv with the final paper including the official link.

**Comment by kjunelee** [comment]
Thank you!
