### ISSUE TITLE
Apply to add a paper

### ISSUE THREAD

**Issue by xiuqhou** [cmhungsteve/Awesome-Transformer-Attention#73]
Hi~ Thanks for maintaining this awesome repository!

We have a new paper [Salience-DETR](https://arxiv.org/abs/2403.16131) proposing a novel transformer-based object detector, which is accepted to CVPR 2024 and we think it is relevant to the [Object Detection](https://github.com/cmhungsteve/Awesome-Transformer-Attention?tab=readme-ov-file#object-detection) part of your repository. We are wondering if you could please add our paper to the collection.

Salience DETR: "Salience DETR: Enhancing Detection Transformer with Hierarchical Salience Filtering Refinement", CVPR, 2024 (Xi'an Jiaotong University) [[Paper](https://arxiv.org/abs/2403.16131)][[PyTorch](https://github.com/xiuqhou/Salience-DETR)]

Thank you very much.

**Comment by cmhungsteve** [comment]
I merged the request.
Thank you for sharing
]
