### ISSUE TITLE
Add code link for DGL in Multi-Modal retrieval (video)

### ISSUE THREAD

**Issue by knightyxp** [cmhungsteve/Awesome-Transformer-Attention#74]
Hi Min-Hung,

I'd like to suggest  adding a code link for DGL in the list for multi-modal retrieval(Video):

* **DGL**: "DGL: Dynamic Global-Local Prompt Tuning for Text-Video Retrieval", AAAI, 2024 (*University of Technology Sydney*). [[Paper](https://arxiv.org/abs/2401.10588)] [[Pytorch](https://github.com/knightyxp/DGL)]

The code is implemented in PyTorch and provides an innovative approach for enhancing text-video retrieval capabilities using dynamic global-local prompt tuning with only 0.53M parameters.

Thank you!

**Comment by cmhungsteve** [comment]
Thank you for sharing.
I have added the code link.
