### ISSUE TITLE
Add new related CVPR 2024 paper

### ISSUE THREAD

**Issue by caiyuanhao1998** [cmhungsteve/Awesome-Transformer-Attention#76]
Thanks for your great contribution. Could you please add this work :

Title: Structure-Aware Sparse-View X-ray 3D Reconstruction
Published in CVPR 2024
Name: SAX-NeRF
Arxiv: https://arxiv.org/abs/2311.10959
Code: https://github.com/caiyuanhao1998/SAX-NeRF

Thank you very much. This work uses a Line Segment-based Transformer to learn a NeRF for 3D X-ray neural rendering.

**Comment by cmhungsteve** [comment]
Thanks for sharing. 
Just added.
