### ISSUE TITLE
[MiPa: Mixed Patch Infrared-Visible Modality Agnostic Object Detection]

### ISSUE THREAD

**Issue by heitorrapela** [cmhungsteve/Awesome-Transformer-Attention#77]
Hello, thanks for the nice list,

Please consider adding our recent work: https://arxiv.org/abs/2404.18849

We propose a Mixed Patches (MiPa), in conjunction with a patch-wise domain agnostic module, which is responsible for learning the best way to find a common representation of both modalities (RGB/Infrared) built on top of DINO (https://github.com/IDEA-Research/DINO).

We have a link for the code, but the work is under review, so we are waiting to release it soon here: https://github.com/heitorrapela/MiPa

**Comment by cmhungsteve** [comment]
Thanks for sharing. 
Just added.

**Comment by heitorrapela** [comment]
Thanks! 👍🏻
