### ISSUE TITLE
Adding official code for STRM

### ISSUE THREAD

**Issue by Anirudh257** [cmhungsteve/Awesome-Transformer-Attention#8]
Hi Steve,
             Thanks for making this excellent repository. Please add our work, Spatio-temporal Relation Modeling for Few-shot Action Recognition:

Paper: https://arxiv.org/pdf/2112.05132.pdf
Github Link: https://github.com/Anirudh257/strm

**Comment by cmhungsteve** [comment]
just added it. Thank you for sharing!

**Comment by Anirudh257** [comment]
Thanks, Steve.
